# Generated by Django 6.0.2 on 2026-02-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО сотрудника')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='Домашний адрес')),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Домашний телефон')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код должности')),
                ('position_name', models.CharField(max_length=100, verbose_name='Наименование должности')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Должностной оклад')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('specialty_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Код специальности')),
                ('specialty_name', models.CharField(max_length=200, verbose_name='Наименование специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_date', models.DateField(verbose_name='Дата взыскания')),
                ('penalty_type', models.CharField(max_length=100, verbose_name='Вид взыскания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='hr.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Взыскание',
                'verbose_name_plural': 'Взыскания',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.position', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='QualificationTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(verbose_name='Дата повышения квалификации')),
                ('qualification_awarded', models.CharField(max_length=100, verbose_name='Присвоена квалификация')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='Номер свидетельства')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='hr.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Повышение квалификации',
                'verbose_name_plural': 'Повышение квалификации',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateField(verbose_name='Дата поощрения')),
                ('reward_type', models.CharField(max_length=100, verbose_name='Вид поощрения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='hr.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Поощрение',
                'verbose_name_plural': 'Поощрения',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('Среднее', 'Среднее'), ('Среднее специальное', 'Среднее специальное'), ('Неполное высшее', 'Неполное высшее'), ('Высшее', 'Высшее'), ('Магистратура', 'Магистратура'), ('Аспирантура', 'Аспирантура')], max_length=50, verbose_name='Уровень образования')),
                ('diploma_number', models.CharField(max_length=50, unique=True, verbose_name='Номер диплома')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квалификация')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='hr.employee', verbose_name='Сотрудник')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='hr.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
    ]
