# Generated by Django 4.2.3 on 2023-09-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('fr', models.CharField(max_length=40, verbose_name='Пункт отправления')),
                ('to', models.CharField(max_length=40, verbose_name='Пункт назначения')),
                ('departure', models.DateTimeField(db_index=True, verbose_name='Время отправления')),
                ('arrive', models.DateTimeField(db_index=True, verbose_name='Время прибытия')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('seats', models.IntegerField(verbose_name='Общее количество мест')),
                ('type', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Уникальный номер пассажира')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('departure', models.DateTimeField(db_index=True, verbose_name='Дата и время отправления')),
                ('purchase', models.DateTimeField(db_index=True, verbose_name='Дата и время продажи')),
                ('booking', models.DateTimeField(db_index=True, verbose_name='Дата и время бронирования')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость')),
                ('category', models.CharField(max_length=15, verbose_name='Тип категории')),
                ('flight_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fboard.flight', verbose_name='Номер рейса')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fboard.vehicle', verbose_name='Тип транспортного средства'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15, verbose_name='Тип')),
                ('seats', models.IntegerField(verbose_name='Количество мест данной категории')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fboard.vehicle', verbose_name='Тип транспортного средства')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('type', 'vehicle'), name='primary_key'),
        ),
    ]
